<?php

if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array(
		'key' => 'group_5d9eb2bed4a42',
		'title' => 'Community',
		'fields' => array(
			array(
				'key' => 'field_5d9eb4a717486',
				'label' => 'location',
				'name' => 'location',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'show_in_graphql' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5d9eb46417485',
				'label' => 'description',
				'name' => 'description',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'show_in_graphql' => 1,
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => 250,
				'rows' => '',
				'new_lines' => '',
			),
			array(
				'key' => 'field_5d9eb35c17483',
				'label' => 'date of event',
				'name' => 'date_of_event',
				'type' => 'date_picker',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'show_in_graphql' => 1,
				'display_format' => 'm/d/Y',
				'return_format' => 'm/d/Y',
				'first_day' => 1,
			),
			array(
				'key' => 'field_5d9eb3fc17484',
				'label' => 'image-card',
				'name' => 'image',
				'type' => 'image',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'show_in_graphql' => 1,
				'return_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
				'min_width' => 270,
				'min_height' => 200,
				'min_size' => '',
				'max_width' => 270,
				'max_height' => 200,
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_5dabb8e1afc89',
				'label' => 'image-modal',
				'name' => 'image',
				'type' => 'image',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'show_in_graphql' => 1,
				'return_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
				'min_width' => 1200,
				'min_height' => 763,
				'min_size' => '',
				'max_width' => 1200,
				'max_height' => 763,
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_5dc864fb5656c',
				'label' => 'comments',
				'name' => 'comments',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'show_in_graphql' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'community',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => 'Collection of images that highlight our community',
		'show_in_graphql' => 1,
		'graphql_field_name' => 'details',
	));

	acf_add_local_field_group(array(
		'key' => 'group_5db7da773204c',
		'title' => 'Description',
		'fields' => array(
			array(
				'key' => 'field_5db7da910ad1a',
				'label' => 'Misison',
				'name' => 'misison',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'show_in_graphql' => 1,
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
			array(
				'key' => 'field_5db7db1b0ad1b',
				'label' => 'Goal',
				'name' => 'goal',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'show_in_graphql' => 1,
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'settings',
				),
				array(
					'param' => 'post',
					'operator' => '==',
					'value' => '171',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_graphql' => 0,
		'graphql_field_name' => 'description',
	));

	acf_add_local_field_group(array(
		'key' => 'group_5dbe05a2062b8',
		'title' => 'Legal',
		'fields' => array(
			array(
				'key' => 'field_5dbe05ad16901',
				'label' => 'Terms of Service',
				'name' => 'tos',
				'type' => 'wysiwyg',
				'instructions' => 'Terms of Service',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'show_in_graphql' => 1,
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
			array(
				'key' => 'field_5dbe069a16902',
				'label' => 'Slack - Code of Conduct',
				'name' => 'conduct_slack',
				'type' => 'wysiwyg',
				'instructions' => 'Code of conduct for Slack',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'show_in_graphql' => 1,
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
			array(
				'key' => 'field_5dbe0964890e5',
				'label' => 'Code of Conduct',
				'name' => 'conduct',
				'type' => 'wysiwyg',
				'instructions' => 'Code of conduct',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'show_in_graphql' => 1,
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
			array(
				'key' => 'field_5dbeacbcd52a7',
				'label' => 'Privacy Policy',
				'name' => 'privacy_policy',
				'type' => 'wysiwyg',
				'instructions' => 'Privacy policy',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'show_in_graphql' => 1,
				'default_value' => '',
				'tabs' => 'all',
				'toolbar' => 'full',
				'media_upload' => 1,
				'delay' => 0,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-legal',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_graphql' => 0,
		'graphql_field_name' => 'legal',
	));

	acf_add_local_field_group(array(
		'key' => 'group_5dbbf7575665e',
		'title' => 'Organization Settings',
		'fields' => array(
			array(
				'key' => 'field_5dbfea3864ac7',
				'label' => 'Announcement',
				'name' => 'announcement',
				'type' => 'textarea',
				'instructions' => 'This announcement will show up on all the pages where the announcement component is utilized.',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'show_in_graphql' => 1,
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => '',
			),
			array(
				'key' => 'field_5dc05e7133368',
				'label' => 'Mission',
				'name' => 'mission',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'show_in_graphql' => 1,
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => '',
			),
			array(
				'key' => 'field_5dc05e7b33369',
				'label' => 'Goal',
				'name' => 'goal',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'show_in_graphql' => 1,
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'new_lines' => '',
			),
			array(
				'key' => 'field_5dbbf76070a08',
				'label' => 'Address',
				'name' => 'address',
				'type' => 'text',
				'instructions' => 'Address for organization Headquarters',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'show_in_graphql' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5dbbf79370a09',
				'label' => 'Email',
				'name' => 'email',
				'type' => 'email',
				'instructions' => 'Public email for community to contact organization',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'show_in_graphql' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array(
				'key' => 'field_5dbbf85f70a0a',
				'label' => 'Phone',
				'name' => 'phone',
				'type' => 'text',
				'instructions' => 'Public phone number for organization',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'show_in_graphql' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5dbbf8e270a0b',
				'label' => 'Map',
				'name' => 'map',
				'type' => 'text',
				'instructions' => 'URL for Google map showing organization\'s location',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'show_in_graphql' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'options_page',
					'operator' => '==',
					'value' => 'acf-options-organization',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_graphql' => 1,
		'graphql_field_name' => 'organization',
	));

	acf_add_local_field_group(array(
		'key' => 'group_5da798bba8d50',
		'title' => 'Post',
		'fields' => array(
			array(
				'key' => 'field_5da79928fff3e',
				'label' => 'author',
				'name' => 'author',
				'type' => 'user',
				'instructions' => 'Set the author(s) of the article',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'show_in_graphql' => 1,
				'role' => array(
					0 => 'author',
					1 => 'administrator',
					2 => 'editor',
					3 => 'contributor',
					4 => 'subscriber',
				),
				'allow_null' => 0,
				'multiple' => 1,
				'return_format' => 'object',
			),
			array(
				'key' => 'field_5da798fefff3c',
				'label' => 'card image',
				'name' => 'card_image',
				'type' => 'image',
				'instructions' => 'This image will be rendered on cards',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'show_in_graphql' => 1,
				'return_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
				'min_width' => 595,
				'min_height' => 200,
				'min_size' => '',
				'max_width' => 595,
				'max_height' => 200,
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_5da79918fff3d',
				'label' => 'hero image',
				'name' => 'hero_image',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'show_in_graphql' => 1,
				'return_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => array(
			0 => 'featured_image',
			1 => 'send-trackbacks',
		),
		'active' => true,
		'description' => 'Article details',
		'show_in_graphql' => 1,
		'graphql_field_name' => 'details',
	));

	acf_add_local_field_group(array(
		'key' => 'group_5d98ce9f9a576',
		'title' => 'Speakers',
		'fields' => array(
			array(
				'key' => 'field_5d98ceb451d16',
				'label' => 'name',
				'name' => 'name',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'show_in_graphql' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5d98cef151d18',
				'label' => 'title',
				'name' => 'title',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'show_in_graphql' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'show_column' => 1,
				'show_column_sortable' => 1,
				'show_column_weight' => 1000,
				'allow_quickedit' => 1,
				'allow_bulkedit' => 0,
			),
			array(
				'key' => 'field_5d98cebd51d17',
				'label' => 'presentation',
				'name' => 'presentation',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'show_in_graphql' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5d98cfb8ea0c7',
				'label' => 'image',
				'name' => 'image',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'show_in_graphql' => 1,
				'return_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
				'min_width' => 250,
				'min_height' => 250,
				'min_size' => '',
				'max_width' => 250,
				'max_height' => 250,
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_5dc382cac27d0',
				'label' => 'date',
				'name' => 'date',
				'type' => 'date_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'show_in_graphql' => 1,
				'display_format' => 'd/m/Y',
				'return_format' => 'd/m/Y',
				'first_day' => 1,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'speakers',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => 'List of all past speakers.',
		'show_in_graphql' => 1,
		'graphql_field_name' => 'details',
	));

	acf_add_local_field_group(array(
		'key' => 'group_5da414a8d315b',
		'title' => 'Sponsors',
		'fields' => array(
			array(
				'key' => 'field_5da415c251ab1',
				'label' => 'company',
				'name' => 'company',
				'type' => 'text',
				'instructions' => 'Company name',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'show_in_graphql' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5da415d651ab2',
				'label' => 'image',
				'name' => 'image',
				'type' => 'image',
				'instructions' => 'Upload sponsoring company logo',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'show_in_graphql' => 1,
				'return_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_5da4169251ab3',
				'label' => 'link',
				'name' => 'link',
				'type' => 'text',
				'instructions' => 'Link to company website',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'show_in_graphql' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'sponsor',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => 'List of all sponsors.',
		'show_in_graphql' => 1,
		'graphql_field_name' => 'details',
	));

	acf_add_local_field_group(array(
		'key' => 'group_5d98c94de542c',
		'title' => 'Staff',
		'fields' => array(
			array(
				'key' => 'field_5d98c98758980',
				'label' => 'name',
				'name' => 'name',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'show_in_graphql' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'show_column' => 1,
				'show_column_sortable' => 1,
				'show_column_weight' => 1000,
				'allow_quickedit' => 1,
				'allow_bulkedit' => 0,
			),
			array(
				'key' => 'field_5d98c9685897f',
				'label' => 'title',
				'name' => 'title',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'show_in_graphql' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
				'show_column' => 1,
				'show_column_sortable' => 1,
				'show_column_weight' => 1000,
				'allow_quickedit' => 1,
				'allow_bulkedit' => 0,
			),
			array(
				'key' => 'field_5d98c99058981',
				'label' => 'image',
				'name' => 'image',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'show_in_graphql' => 1,
				'return_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
				'min_width' => 250,
				'min_height' => 250,
				'min_size' => '',
				'max_width' => 250,
				'max_height' => 250,
				'max_size' => '',
				'mime_types' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'staff',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => 'List of staff members.',
		'show_in_graphql' => 1,
		'graphql_field_name' => 'details',
	));

	acf_add_local_field_group(array(
		'key' => 'group_5da41800e271f',
		'title' => 'Stories',
		'fields' => array(
			array(
				'key' => 'field_5da41a07d0ad9',
				'label' => 'name',
				'name' => 'name',
				'type' => 'text',
				'instructions' => 'Member name',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'show_in_graphql' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5da41a17d0ada',
				'label' => 'title',
				'name' => 'title',
				'type' => 'text',
				'instructions' => 'Professional title',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'show_in_graphql' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5da41ad2d0adb',
				'label' => 'content',
				'name' => 'content',
				'type' => 'text',
				'instructions' => '',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'show_in_graphql' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5da4198bd0ad8',
				'label' => 'image',
				'name' => 'image',
				'type' => 'image',
				'instructions' => 'Member image',
				'required' => 1,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'show_in_graphql' => 1,
				'return_format' => 'url',
				'preview_size' => 'medium',
				'library' => 'all',
				'min_width' => 430,
				'min_height' => 470,
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_5da41b60d0adc',
				'label' => 'linkedin',
				'name' => 'linkedin',
				'type' => 'url',
				'instructions' => 'LinkedIn',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'show_in_graphql' => 1,
				'default_value' => '',
				'placeholder' => '',
			),
			array(
				'key' => 'field_5da41b96d0add',
				'label' => 'github',
				'name' => 'github',
				'type' => 'url',
				'instructions' => 'Github',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'show_in_graphql' => 1,
				'default_value' => '',
				'placeholder' => '',
			),
			array(
				'key' => 'field_5da41ba1d0ade',
				'label' => 'twitter',
				'name' => 'twitter',
				'type' => 'url',
				'instructions' => 'Twitter',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'show_in_graphql' => 1,
				'default_value' => '',
				'placeholder' => '',
			),
			array(
				'key' => 'field_5da41bb1d0adf',
				'label' => 'instagram',
				'name' => 'instagram',
				'type' => 'text',
				'instructions' => 'Instagram',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'show_in_graphql' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_5da41bc1d0ae0',
				'label' => 'facebook',
				'name' => 'facebook',
				'type' => 'url',
				'instructions' => 'Facebook',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'show_in_graphql' => 1,
				'default_value' => '',
				'placeholder' => '',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'story',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => 'List of success stories from members.',
		'show_in_graphql' => 1,
		'graphql_field_name' => 'details',
	));

	acf_add_local_field_group(array(
		'key' => 'group_5d98e0e5c9a74',
		'title' => 'Ordering',
		'fields' => array(
			array(
				'key' => 'field_5d98e0f1a8669',
				'label' => 'position',
				'name' => 'position',
				'type' => 'number',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'show_in_graphql' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
				'show_column' => 1,
				'show_column_sortable' => 1,
				'show_column_weight' => 1000,
				'allow_quickedit' => 1,
				'allow_bulkedit' => 0,
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'speakers',
				),
			),
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'staff',
				),
			),
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'post',
				),
			),
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'community',
				),
			),
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'story',
				),
			),
			array(
				array(
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'sponsor',
				),
			),
		),
		'menu_order' => 10,
		'position' => 'side',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => 'Dictates the order objects will be rendered.',
		'show_in_graphql' => 1,
		'graphql_field_name' => 'order',
	));

endif;
